# Generated by Django 4.0.6 on 2022-08-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='watched',
            field=models.IntegerField(default=0),
        ),
    ]
